USE [Springboard]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.League
(
	LeagueId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_League PRIMARY KEY CLUSTERED (LeagueId),
	LeagueName VARCHAR(100) NOT NULL,
)
GO

CREATE TABLE dbo.Season
(
	SeasonId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Season PRIMARY KEY CLUSTERED (SeasonId),
	SeasonName VARCHAR(100) NOT NULL
)
GO

CREATE TABLE dbo.LeagueSeason
(
	LeagueId INT NOT NULL CONSTRAINT FK_LeagueSeason_League FOREIGN KEY(LeagueId) REFERENCES dbo.League(LeagueId),
	SeasonId INT NOT NULL CONSTRAINT FK_LeagueSeason_Season FOREIGN KEY(SeasonId) REFERENCES dbo.Season(SeasonId),
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	CONSTRAINT PK_LeagueSeason PRIMARY KEY CLUSTERED (LeagueId, SeasonId)
)
GO

CREATE NONCLUSTERED INDEX IX_LeagueSeason_SeasonId ON dbo.LeagueSeason(SeasonId)
GO

CREATE TABLE dbo.Team
(
	TeamId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Team PRIMARY KEY CLUSTERED (TeamId),
	TeamName VARCHAR(100) NOT NULL,
	TeamCity VARCHAR(100) NOT NULL
)
GO

CREATE TABLE dbo.Player
(
	PlayerId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Player PRIMARY KEY CLUSTERED (PlayerId),
	FullName VARCHAR(250) NOT NULL,
	TeamId INT NOT NULL CONSTRAINT FK_Player_Team FOREIGN KEY(TeamId) REFERENCES dbo.Team(TeamId)
)
GO

CREATE TABLE dbo.Referee
(
	RefereeId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Referee PRIMARY KEY CLUSTERED (RefereeId),
	FullName VARCHAR(250) NOT NULL
)
GO

CREATE TABLE dbo.Game
(
	GameId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Game PRIMARY KEY CLUSTERED (GameId),
	GameDate DATE NOT NULL,
	LeagueId INT NOT NULL CONSTRAINT FK_Game_League FOREIGN KEY(LeagueId) REFERENCES dbo.League(LeagueId),
	SeasonId INT NOT NULL CONSTRAINT FK_Game_Season FOREIGN KEY(SeasonId) REFERENCES dbo.Season(SeasonId),
	HomeTeamId INT NOT NULL CONSTRAINT FK_Game_Team1 FOREIGN KEY(HomeTeamId) REFERENCES dbo.Team(TeamId),
	AwayTeamId INT NOT NULL CONSTRAINT FK_Game_Team2 FOREIGN KEY(AwayTeamId) REFERENCES dbo.Team(TeamId)
)
GO

CREATE TABLE dbo.RefereeLineup
(	
	GameId INT NOT NULL CONSTRAINT FK_RefereeLineup_Game FOREIGN KEY(GameId) REFERENCES dbo.Game(GameId),
	RefereeID INT NOT NULL CONSTRAINT FK_RefereeLineup_Referee FOREIGN KEY(RefereeID) REFERENCES dbo.Referee(RefereeID),
	RefereeTypeID INT NOT NULL,
	CONSTRAINT PK_RefereeLineup PRIMARY KEY CLUSTERED (GameId, RefereeId)
)
GO

CREATE NONCLUSTERED INDEX IX_RefereeLineup_RefereeId ON dbo.RefereeLineup(RefereeId)
GO

CREATE TABLE dbo.PlayerLineup
(
	GameId INT NOT NULL CONSTRAINT FK_PlayerLineup_Game FOREIGN KEY(GameId) REFERENCES dbo.Game(GameId),
	PlayerId INT NOT NULL CONSTRAINT FK_PlayerLineup_Player FOREIGN KEY(PlayerId) REFERENCES dbo.Player(PlayerId),
	IsHomeTeam TINYINT NOT NULL,
	CONSTRAINT PK_PlayerLineup PRIMARY KEY CLUSTERED (GameId, PlayerId)
)
GO

CREATE NONCLUSTERED INDEX IX_PlayerLineup_PlayerId ON dbo.PlayerLineup(PlayerId)
GO

CREATE TABLE dbo.Goal
(
	GoalId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Goal PRIMARY KEY CLUSTERED (GoalId),
	GameId INT NOT NULL CONSTRAINT FK_Goal_Game FOREIGN KEY(GameId) REFERENCES dbo.Game(GameId),
	PlayerId INT NOT NULL CONSTRAINT FK_Goal_Player FOREIGN KEY(PlayerId) REFERENCES dbo.Player(PlayerId),
	GoalMinute SMALLINT NOT NULL
)
GO
